# Generated by Django 6.0.4 on 2026-05-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_savedroadmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedroadmap',
            name='resources',
            field=models.JSONField(default=list),
        ),
    ]
