# Generated by Django 6.0.4 on 2026-06-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0003_savedroadmap_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedroadmap',
            name='user_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
